plagchecker api first commit
mlsect-dojo/plagchecker pull request #12
Opened 2021-09-06 10:34 UTC by theotff

Сделал первые два эндпойнта, архивам выдается название через uuid и они сохраняются в папке, а в базу пишется путь. Вторые два эндпойнта просто заглушки, пока нет алгоритмов.

2021-09-06 11:18 UTC, ARQtty requested changes
Стоит сделать отдельный модуль работы с бд. Там были бы и .sql файлы для создания/миграций бд, и классы взаимодействия с хранилищем

Все запускаемые файлы (в том числе сервер) должны лежать в корне

Бэк является одной из составляющих сервиса, поэтому весь его код, кроме запускаемого из корня, должен лежать в одной папке. Её внутренняя структура - на усмотрение разработчика

2021-09-06 15:14 UTC, theotff commented
Вынес сервер в корень. Сделал отдельный модуль взаимодействия с бд

2021-09-06 18:57 UTC, ARQtty requested changes
Возможно стоит сделать методы не static

2021-09-06 18:57 UTC, ARQtty commented on api/utils/db.py
> +db_path = f'{pathlib.Path(__file__).parent.resolve()}/../plagchecker.db'
зачем писать `../` после пути, если можно лишний раз вызвать `.parent()`?

2021-09-06 18:57 UTC, ARQtty commented on api/utils/db.py
> +class SQLite():
Не очень трактуемое название. Мб что-то вроде "SQLiteConnector" лучше бы доносило задачу класса

2021-09-06 18:57 UTC, ARQtty commented on api/utils/db.py
> +    @staticmethod
Нужно ли делать методы статичными, а потом обращаться к глобальной переменной? Возможно обычный метод с обращением к self был бы легче для понимания

2021-09-06 18:57 UTC, ARQtty commented on api/utils/db.py
> +    async def insert_lab(filename):
стоит указывать typing hints для аргументов и возвращаемого типа данных

2021-09-06 18:57 UTC, ARQtty commented on api/utils/db.py
> +    async def delete_lab(lab_id):
typing hints

2021-09-06 19:26 UTC, theotff commented on api/utils/db.py
> +    @staticmethod
Тогда логичнее сделать classmethod, чтобы обращаться к классовой переменной, потому что сервер сделан на декораторах, и метод с self оттуда не вызвать

2021-09-07 17:46 UTC, ARQtty approved these changes

2021-09-08 07:00 UTC, merged